from __future__ import annotations

from typing import Any

from nion.model_management.models import (
    ProviderTemplate,
    ProviderTemplateCategoryMembership,
)
from nion.model_management.repository import ModelManagementRepository


BUILTIN_PROVIDER_TEMPLATES: list[dict[str, Any]] = [
    {
        "code": "minimax-cn",
        "name": "MiniMax",
        "description": "国产领先的 AI 编程模型，性价比高，新手友好。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "sort_order": 10,
    },
    {
        "code": "zhipu",
        "name": "智谱",
        "description": "智谱 GLM 大模型，国内老牌 AI 厂商。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "badge": "推荐",
        "sort_order": 20,
    },
    {
        "code": "deepseek",
        "name": "DeepSeek",
        "description": "DeepSeek 深度求索，按量计费。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "sort_order": 30,
    },
    {
        "code": "stepfun",
        "name": "阶跃星辰",
        "description": "阶跃星辰，Step 系列模型。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "sort_order": 40,
    },
    {
        "code": "longcat",
        "name": "Longcat",
        "description": "长上下文化服务。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "sort_order": 50,
    },
    {
        "code": "kimi-coding-plan",
        "name": "Kimi Coding Plan",
        "description": "Kimi 智能助手的编程版，月之暗面出品。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "badge": "推荐",
        "sort_order": 60,
    },
    {
        "code": "moonshot-cn",
        "name": "Moonshot",
        "description": "月之暗面开放平台，按量计费。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "sort_order": 70,
    },
    {
        "code": "bailian-coding-plan",
        "name": "百炼 Coding Plan",
        "description": "阿里云百炼，通义千问系列模型。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "sort_order": 80,
    },
    {
        "code": "bailing",
        "name": "百灵 (BaiLing)",
        "description": "支付宝百灵，Ling 系列模型。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "sort_order": 90,
    },
    {
        "code": "mimo",
        "name": "小米 MiMo",
        "description": "小米 MiMo 开放平台。",
        "category": "domestic",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "sort_order": 100,
    },
    {
        "code": "doubao",
        "name": "火山方舟 (DouBao)",
        "description": "字节跳动火山方舟，豆包系列模型。",
        "category": "aggregator",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "badge": "推荐",
        "sort_order": 10,
    },
    {
        "code": "modelscope",
        "name": "ModelScope",
        "description": "魔搭社区，阿里云模型推理服务。",
        "category": "aggregator",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "sort_order": 20,
    },
    {
        "code": "siliconflow-cn",
        "name": "硅基流动",
        "description": "硅基流动国内版，国产模型聚合。",
        "category": "aggregator",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "sort_order": 30,
    },
    {
        "code": "minimax-global",
        "name": "MiniMax (EN)",
        "description": "MiniMax 国际版，适合海外用户。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 10,
    },
    {
        "code": "z-ai",
        "name": "Z.ai",
        "description": "智谱国际版，适合海外用户。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 20,
    },
    {
        "code": "openrouter",
        "name": "OpenRouter",
        "description": "多模型聚合平台，支持 Claude/GPT 等。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 30,
    },
    {
        "code": "siliconflow-global",
        "name": "SiliconFlow",
        "description": "硅基流动国际版，海外模型聚合。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 40,
    },
    {
        "code": "zenmux",
        "name": "ZenMux",
        "description": "自动路由聚合，支持故障转移。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 50,
    },
    {
        "code": "aihubmix",
        "name": "AiHubMix",
        "description": "模型聚合服务，支持 Claude 等。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 60,
    },
    {
        "code": "nvidia-build",
        "name": "Nvidia",
        "description": "Nvidia Build API，GPU 推理平台。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 70,
    },
    {
        "code": "dmxapi",
        "name": "DMXAPI",
        "description": "国内镜像代理，支持 Claude 等海外模型。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 80,
    },
    {
        "code": "groq",
        "name": "Groq",
        "description": "高速推理平台，专注开源模型。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 90,
    },
    {
        "code": "cerebras",
        "name": "Cerebras",
        "description": "高速推理芯片平台。",
        "category": "global",
        "protocol": "openai-compatible",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "network_notice": "请先提前自行配置网络服务或打开 TUN 模式",
        "sort_order": 100,
    },
    {
        "code": "ollama",
        "name": "Ollama",
        "description": "本地运行开源模型，无需 API 密钥。",
        "category": "local",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "requires_api_key": False,
        "sort_order": 10,
    },
    {
        "code": "lm-studio",
        "name": "LM Studio",
        "description": "本地模型管理工具，可视化操作。",
        "category": "local",
        "protocol": "openai-compatible",
        "supports_model_discovery": True,
        "discovery_mode": "api",
        "requires_api_key": False,
        "sort_order": 20,
    },
    {
        "code": "custom-provider",
        "name": "自定义供应商",
        "description": "配置自定义 API 兼容的供应商。",
        "protocol": "custom",
        "base_url_mode": "editable",
        "supports_model_discovery": False,
        "discovery_mode": "manual",
        "allows_multiple_instances": True,
        "sort_order": 999,
    },
]

TEMPLATE_CATEGORY_MEMBERSHIPS: dict[str, tuple[str, ...]] = {
    "minimax-cn": ("domestic",),
    "zhipu": ("domestic",),
    "deepseek": ("domestic",),
    "stepfun": ("domestic",),
    "longcat": ("domestic",),
    "kimi-coding-plan": ("domestic",),
    "moonshot-cn": ("domestic",),
    "bailian-coding-plan": ("domestic",),
    "bailing": ("domestic",),
    "mimo": ("domestic",),
    "doubao": ("aggregator",),
    "modelscope": ("aggregator",),
    "siliconflow-cn": ("aggregator",),
    "minimax-global": ("global",),
    "z-ai": ("global",),
    "openrouter": ("global",),
    "siliconflow-global": ("global",),
    "zenmux": ("global",),
    "aihubmix": ("global",),
    "nvidia-build": ("global",),
    "dmxapi": ("global",),
    "groq": ("global",),
    "cerebras": ("global",),
    "ollama": ("local",),
    "lm-studio": ("local",),
    "custom-provider": ("domestic", "aggregator", "global", "local"),
}


def seed_builtin_provider_templates(repo: ModelManagementRepository) -> None:
    for template_payload in BUILTIN_PROVIDER_TEMPLATES:
        template = ProviderTemplate.model_validate(template_payload)
        saved = repo.upsert_provider_template(template)
        for category_index, category in enumerate(
            TEMPLATE_CATEGORY_MEMBERSHIPS[saved.code],
            start=1,
        ):
            repo.save_category_membership(
                ProviderTemplateCategoryMembership(
                    provider_template_id=saved.id,
                    category=category,
                    sort_order=saved.sort_order * 10 + category_index,
                )
            )
