from __future__ import annotations

from nion.capability_backbone.models import SystemCapabilityObject


def build_system_object_registry() -> list[dict]:
    return [
        SystemCapabilityObject(
            kind="document",
            id="identity_document",
            label="Identity 文档",
            actions=["read", "write"],
            query_tool="read_identity_document",
            mutation_tool="write_identity_document",
            cli_command="nion documents identity read",
            aliases=["identity", "identify", "身份", "身份文件", "identity.md", "identify.md"],
            description="用户身份主档文档。",
        ).model_dump(),
        SystemCapabilityObject(
            kind="document",
            id="soul_document",
            label="Soul 文档",
            actions=["read", "write"],
            query_tool="read_soul_document",
            mutation_tool="write_soul_document",
            cli_command="nion documents soul read",
            aliases=["soul", "灵魂", "人格", "soul.md", "助手风格"],
            description="助手长期人格文档。",
        ).model_dump(),
        SystemCapabilityObject(
            kind="document",
            id="active_memory_document",
            label="Active Memory 文档",
            actions=["read"],
            query_tool="read_active_memory_document",
            cli_command="nion documents memory read",
            aliases=["memory", "记忆", "memory.md", "活跃记忆"],
            description="助手维护的活跃记忆文档。",
        ).model_dump(),
        SystemCapabilityObject(
            kind="automation",
            id="automation_registry",
            label="自动化任务",
            actions=["list", "create", "update"],
            query_tool="list_automations",
            mutation_tool="create_automation",
            cli_command="nion automations list --json",
            aliases=["定时任务", "自动任务", "自动化", "提醒"],
            description="当前自动化与定时任务集合。",
        ).model_dump(),
        SystemCapabilityObject(
            kind="system_status",
            id="model_catalog",
            label="模型目录",
            actions=["list"],
            query_tool="get_model_catalog",
            cli_command="nion models list --json",
            aliases=["模型", "模型列表", "有哪些模型"],
            description="当前可用模型目录。",
        ).model_dump(),
        SystemCapabilityObject(
            kind="system_status",
            id="bridge_status",
            label="桥接状态",
            actions=["status"],
            query_tool="get_bridge_status",
            cli_command="nion bridges status --json",
            aliases=["bridge", "桥接", "连接", "桥接状态", "在线桥接"],
            description="当前桥接与连接状态。",
        ).model_dump(),
        SystemCapabilityObject(
            kind="system_status",
            id="skill_registry",
            label="技能目录",
            actions=["list"],
            query_tool="get_skill_registry",
            cli_command="nion skills list --json",
            aliases=["skill", "skills", "技能", "技能列表"],
            description="当前可用技能目录。",
        ).model_dump(),
        SystemCapabilityObject(
            kind="notebook",
            id="notebook_registry",
            label="笔记目录",
            actions=["list", "create"],
            query_tool="list_notebook_notes",
            mutation_tool="create_notebook_note",
            cli_command="nion notebook list --json",
            aliases=["笔记", "notebook", "记一条笔记"],
            description="当前笔记与知识库目录。",
        ).model_dump(),
    ]
